#!/bin/bash
# Copyright 2025 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source /etc/satlab/satlab.conf

##################################################################
echo "Waiting for interface $INTERNAL_PORT_TO_DUTS to become available..."
timeout=30
count=0
while [ ! -d "/sys/class/net/$INTERNAL_PORT_TO_DUTS" ]; do
    if [ $count -ge $timeout ]; then
        echo "Error: Interface $INTERNAL_PORT_TO_DUTS not found after ${timeout}s."
        exit 1
    fi
    sleep 1
    ((count++))
done
echo "Interface $INTERNAL_PORT_TO_DUTS is ready. Proceeding with bridge creation."
##################################################################
# Wait for the physical interface to be recognized by the kernel
timeout=15
count=0
while [ ! -d "/sys/class/net/${INTERNAL_PORT_TO_DUTS}" ]; do
    if [ $count -ge $timeout ]; then
        echo "Error: Physical interface ${INTERNAL_PORT_TO_DUTS} not found."
        exit 1
    fi
    sleep 1
    ((count++))
done

# Create the bridge if it doesn't exist
if ! ip link show "${DHCPD_IFACE}" >/dev/null 2>&1; then
    echo "Creating bridge ${DHCPD_IFACE}..."
    ip link add name "${DHCPD_IFACE}" type bridge
fi

ip link set dev "${DHCPD_IFACE}" type bridge forward_delay 0
ip link set dev "${DHCPD_IFACE}" allmulticast on
ip link set dev "${INTERNAL_PORT_TO_DUTS}" allmulticast on
ip link set dev "${INTERNAL_PORT_TO_DUTS}" up

# Add the physical port to the bridge (if not already a member)
if [[ "$(cat /sys/class/net/${INTERNAL_PORT_TO_DUTS}/master/uevent 2>/dev/null)" != *"INTERFACE=${DHCPD_IFACE}"* ]]; then
    echo "Adding ${INTERNAL_PORT_TO_DUTS} to ${DHCPD_IFACE}..."
    ip link set dev "${INTERNAL_PORT_TO_DUTS}" master "${DHCPD_IFACE}"
else
    echo "${INTERNAL_PORT_TO_DUTS} is already a member of ${DHCPD_IFACE}."
fi

# Assign IP Address to the bridge
echo "Assigning IP ${SERVER_ADDRESS} to ${DHCPD_IFACE}..."
ip addr replace "${SERVER_ADDRESS}/${SERVER_NETMASK}" dev "${DHCPD_IFACE}"
ip link set dev "${DHCPD_IFACE}" up
############################################################
# You can't have --rm and --restart on a docker run command.
# However this means that on a non clean shutdown the dhcp container is
# restarted, this causes internal/external network detection issues and
# put the Satlab in a bad state.
# On boot get rid of any prior containers and make sure we have the latest
# dhcp container.
docker rm --force dhcp || true
docker pull ${DHCP_DOCKER_IMAGE}
docker run --name dhcp -d \
    -v leases:/var/lib/misc -d \
    --restart always \
    --cap-add=NET_ADMIN \
    --network host \
    ${DHCP_DOCKER_IMAGE} \
    --interface ${DHCPD_IFACE} \
    --bind-interfaces \
    --log-dhcp

# Set sharing between interfaces.
iptables -w -t nat -A POSTROUTING -o "${EXTERNAL_PORT_TO_INTERNET}" -j MASQUERADE
iptables -w -A FORWARD -i "${EXTERNAL_PORT_TO_INTERNET}" -o ${DHCPD_IFACE} -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -w -A FORWARD -i ${DHCPD_IFACE} -o "${EXTERNAL_PORT_TO_INTERNET}" -j ACCEPT
ifconfig "${INTERNAL_PORT_TO_DUTS}" up
iptables -w -P FORWARD ACCEPT
