#!/bin/bash
# Copyright 2025 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG="$(dirname "$0")/satlab.conf"
function set_config(){
    sed -i "s/^\($1\s*=\s*\).*\$/\1$2/" $CONFIG
}

#
# Data provided by user as part of setup process.
#
# Name that is set for the satlab and the drone.
HOST_IDENTIFIER=
DRONE_HOSTNAME=satlab-${HOST_IDENTIFIER}
# Interface that is connected to the internet
EXTERNAL_PORT_TO_INTERNET=
# Interface that is connected to DUT
INTERNAL_PORT_TO_DUTS=

#
# DO NOT change below settings unless instructed
#
DHCPD_IFACE=br0
SERVER_ADDRESS=192.168.231.1
SERVER_NETMASK=255.255.255.0
REMOTE_ACCESS_SSH_PORT=22

LABEL=release
#
# Docker images used in the scripts.
#
DHCP_DOCKER_IMAGE=us-docker.pkg.dev/chromeos-partner-moblab/satlab/satlab-dhcp:${LABEL}
COMPOSE_DOCKER_IMAGE=us-docker.pkg.dev/chromeos-partner-moblab/satlab/satlab-compose:${LABEL}
REMOTE_ACCESS_IMAGE=us-docker.pkg.dev/chromeos-partner-moblab/satlab/satlab_remote_access:${LABEL}
CLOUD_SDK_IMAGE=google/cloud-sdk:536.0.0-slim

#
# Other settings used in the scripts.
#
VOLUME_KEYS_FOLDER=/home/satlab/keys/
DOCKER_CERT_PATH=/var/docker/certs
