# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

version: "3"
services:
  watchtower:
    container_name: watchtower
    image: ${REGISTRY_URI:-us-docker.pkg.dev/chromeos-partner-moblab/satlab}/watchtower:${WATCHTOWER:-release}
    restart: unless-stopped
    environment:
      - DOCKER_CONFIG=/config
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_LIFECYCLE_HOOKS=true
      - WATCHTOWER_MONITOR_ONLY=${WATCHTOWER_MONITOR_ONLY}
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_REVIVE_STOPPED=true
    volumes:
      - docker_config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ulimits:
      nofile:
        soft: 10000
        hard: 16384
volumes:
  docker_config:
    external: True