# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

version: "3"
services:
  ##############################################################################conf-creator
  conf_creator:
    container_name: conf-creator
    image: ${SFP_REGISTRY_URI:-us-docker.pkg.dev/chromeos-partner-moblab/satlab-for-partners}/conf_creator:${CONF_CREATOR:-release}
    environment:
      - DOCKER_GCS_IMAGE_STORAGE_SERVER=${GCS_IMAGE_BUCKET:-chromeos-image-archive}
    labels:
      - "skip.while.pruning.docker.system=yes"
    volumes:
      - nginx_configs:/mnt/conf/nginx:rw
  ##############################################################################drone
  drone:
    container_name: drone
    image: ${SFP_REGISTRY_URI:-us-docker.pkg.dev/chromeos-partner-moblab/satlab-for-partners}/drone:${SATLAB_DRONE:-release}
    environment:
      - DOCKER_DRONE_QUEEN_SERVICE=drone-queen-prod.appspot.com
      - DOCKER_DRONE_SWARMING_SERVER_URL=https://chromeos-swarming.appspot.com
      - DOCKER_DRONE_ADMIN_SERVICE=chromeos-skylab-bot-fleet.appspot.com
      - DOCKER_DRONE_INVENTORY_ENVIRONMENT=prod
      - DOCKER_DRONE_AGENT_DUT_CAPACITY=${DRONE_AGENT_DUT_CAPACITY:-10}
      - DOCKER_DRONE_INVENTORY_SERVICE=cros-lab-inventory.appspot.com
      - DOCKER_DRONE_UFS_SERVICE=ufs.api.cr.dev
      - DOCKER_DRONE_AGENT_HIVE=${DRONE_HOSTNAME:-satlab-drone}
      - DOCKER_DRONE_LABPACK_DIR=/usr/local/labpack
      - DOCKER_DRONE_CACHESERVER_IP=192.168.100.1
      - DOCKER_DRONE_SUBNET=192.168.231.0/24
      - SERVOD_CONTAINER_LABEL=${SERVOD_CONTAINER_LABEL:-release}
      - DOCKER_SERVOD_DEBUG_MODE=0
      - DOCKER_DEFAULT_NETWORK=default_satlab
      - DOCKER_DRONE_SERVER_NAME=${SATLAB_HOST_IP:-satlab-drone}
      - DOCKER_DNS_SERVER=192.168.100.51
      - DOCKER_DRONE_PRIVATE_SSH_KEYS_PATH=/creds/ssh_keys/partner_testing_rsa
      - DOCKER_DRONE_AGENT_BOT_PREFIX=${BOT_PREFIX:-crossk-}
      - DOCKER_DRONE_AGENT_TSMON_CREDENTIAL_PATH=${TSMON_CREDENTIAL_PATH:-}
      - DOCKER_DRONE_AGENT_TSMON_ENDPOINT=${TSMON_END_POINT:-}
      - DOCKER_SHIVAS_NAMESPACE=${UFS_NAMESPACE:-os}
      - DOCKER_GCS_IMAGE_STORAGE_SERVER=${GCS_IMAGE_BUCKET:-}
      - DOCKER_DRONE_RECOVERY_VERSIONS_DIR=/creds/service_accounts/recovery_versions/
    privileged: true
    hostname: ${DRONE_HOSTNAME:-satlab-drone}
    restart: always
    volumes:
      - ssp:/usr/local/autotest/containers/ssp_volume:rw
      - satlab_keys:/creds/service_accounts:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/run/docker.sock:/var/docker.sock:rw
      - servod_profile:/var/servod/profile/:rw
      - containers:/var/lib/containers:rw
      - partner_testing_rsa:/creds/ssh_keys:rw
    # TODO (prasadv): Make static ip addresses higher numbers
    # so that the lower number are available for dhcp to assign it
    # to dynamically created containers such as servod container
    networks:
      satlab:
        ipv4_address: 192.168.100.10
    dns:
      - 192.168.100.51
    depends_on:
      - dns
      - partner_testing_rsa
  ##############################################################################dns
  dns:
    container_name: dns
    image: ${COMMON_CORE_URI:-gcr.io/chromeos-partner-moblab}/moblab-dns:${DNS:-release}
    restart: unless-stopped
    volumes:
        - logs:/var/log/
        - dut_hosts:/etc/dut_hosts:rw
    command: ['/usr/sbin/dnsmasq', '--no-daemon', '-u', 'moblab', '-g', 'moblab', '-H', '/etc/dut_hosts/hosts', '--log-queries', '--log-debug']
    networks:
      satlab:
        ipv4_address: 192.168.100.51
  ##############################################################################downloader
  downloader:
    container_name: downloader
    image: ${SFP_REGISTRY_URI:-us-docker.pkg.dev/chromeos-partner-moblab/satlab-for-partners}/downloader:${DOWNLOADER:-release}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - images:/home/chromeos-test/images
      - satlab_keys:/creds/service_accounts
    command: ['--credential-file', '/creds/service_accounts/pubsub-key-do-not-delete.json', '--address', ':8887', '--cache-server-url', 'http://192.168.100.3:8082']
    networks:
      satlab:
        ipv4_address: 192.168.100.2
    dns:
      - 192.168.100.51
    depends_on:
      - dns
  ##############################################################################ngix
  nginx:
    container_name: nginx
    image: ${SFP_REGISTRY_URI:-us-docker.pkg.dev/chromeos-partner-moblab/satlab-for-partners}/nginx:${NGINX:-release}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - nginx_logs:/var/log/nginx
      - cache:/var/cache/nginx
      - nginx_configs:/mnt/conf/nginx:ro
    ports:
      - "8082:8082"
    command: ['nginx', '-g', 'daemon off;', '-c', '/mnt/conf/nginx/nginx.conf']
    networks:
      satlab:
        ipv4_address: 192.168.100.3
    dns:
      - 192.168.100.51
    extra_hosts:
      - "cacheserver:192.168.100.1"
    depends_on:
      - conf_creator
      - dns
      - downloader
  ##############################################################################openssh_server
  openssh_server:
    container_name: openssh_server
    image: ${SFP_REGISTRY_URI:-us-docker.pkg.dev/chromeos-partner-moblab/satlab-for-partners}/openssh_server:${OPENSSH_SERVER:-release}
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=false
      - USER_NAME=chromeos-test
    ports:
      - "2222:2222"
    dns:
      - 192.168.100.51
  ##############################################################################dut_key
  partner_testing_rsa:
    container_name: partner_testing_rsa
    image: us-docker.pkg.dev/chromeos-partner-moblab/satlab-for-partners/partner_testing_rsa:${PARTNER_TESTING_RSA:-release}
    labels:
      - "skip.while.pruning.docker.system=yes"
    volumes:
      - partner_testing_rsa:/creds/ssh_keys:rw
  ##############################################################################volumes
volumes:
    logs: {}
    images: {}
    cache: {}
    dut_hosts: {}
    nginx_configs: {}
    servod_profile: {}
    satlab_keys:
      external: True
    ssp: {}
    containers: {}
    nginx_logs: {}
    partner_testing_rsa: {}
  ##############################################################################networks
networks:
  satlab:
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
