# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import hostservice_pb2 as moblab__common_dot_proto_dot_hostservice__pb2

class MoblabHostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_host_identifier = channel.unary_unary(
                '/moblab.MoblabHostService/get_host_identifier',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.HostIdentifierResponse.FromString,
                )
        self.is_service_running = channel.unary_unary(
                '/moblab.MoblabHostService/is_service_running',
                request_serializer=moblab__common_dot_proto_dot_hostservice__pb2.ServiceRunningRequest.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.ServiceRunningResponse.FromString,
                )
        self.get_disk_info = channel.unary_unary(
                '/moblab.MoblabHostService/get_disk_info',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.DiskInfoResponse.FromString,
                )
        self.get_cpu_temperature = channel.unary_unary(
                '/moblab.MoblabHostService/get_cpu_temperature',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.CpuTemperatureResponse.FromString,
                )
        self.get_ip = channel.unary_unary(
                '/moblab.MoblabHostService/get_ip',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.IpResponse.FromString,
                )
        self.get_external_mac_address = channel.unary_unary(
                '/moblab.MoblabHostService/get_external_mac_address',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.ExternalMacAddressResponse.FromString,
                )
        self.check_for_system_update = channel.unary_unary(
                '/moblab.MoblabHostService/check_for_system_update',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.get_system_update_status = channel.unary_unary(
                '/moblab.MoblabHostService/get_system_update_status',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.SystemUpdateStatusResponse.FromString,
                )
        self.install_system_update = channel.unary_unary(
                '/moblab.MoblabHostService/install_system_update',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.SystemUpdateInstallResponse.FromString,
                )
        self.reboot = channel.unary_unary(
                '/moblab.MoblabHostService/reboot',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.factory_reset = channel.unary_unary(
                '/moblab.MoblabHostService/factory_reset',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.get_system_version = channel.unary_unary(
                '/moblab.MoblabHostService/get_system_version',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.SystemVersionResponse.FromString,
                )
        self.get_api_version = channel.unary_unary(
                '/moblab.MoblabHostService/get_api_version',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.GetApiVersionResponse.FromString,
                )
        self.get_disk_usage_stats = channel.unary_unary(
                '/moblab.MoblabHostService/get_disk_usage_stats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.GetDiskUsageStatsResponse.FromString,
                )
        self.stop_ui = channel.unary_unary(
                '/moblab.MoblabHostService/stop_ui',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class MoblabHostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_host_identifier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_service_running(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_disk_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_cpu_temperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_ip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_external_mac_address(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def check_for_system_update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_system_update_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def install_system_update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reboot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def factory_reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_system_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_api_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_disk_usage_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_ui(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoblabHostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_host_identifier': grpc.unary_unary_rpc_method_handler(
                    servicer.get_host_identifier,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.HostIdentifierResponse.SerializeToString,
            ),
            'is_service_running': grpc.unary_unary_rpc_method_handler(
                    servicer.is_service_running,
                    request_deserializer=moblab__common_dot_proto_dot_hostservice__pb2.ServiceRunningRequest.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.ServiceRunningResponse.SerializeToString,
            ),
            'get_disk_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_disk_info,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.DiskInfoResponse.SerializeToString,
            ),
            'get_cpu_temperature': grpc.unary_unary_rpc_method_handler(
                    servicer.get_cpu_temperature,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.CpuTemperatureResponse.SerializeToString,
            ),
            'get_ip': grpc.unary_unary_rpc_method_handler(
                    servicer.get_ip,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.IpResponse.SerializeToString,
            ),
            'get_external_mac_address': grpc.unary_unary_rpc_method_handler(
                    servicer.get_external_mac_address,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.ExternalMacAddressResponse.SerializeToString,
            ),
            'check_for_system_update': grpc.unary_unary_rpc_method_handler(
                    servicer.check_for_system_update,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_system_update_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_system_update_status,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.SystemUpdateStatusResponse.SerializeToString,
            ),
            'install_system_update': grpc.unary_unary_rpc_method_handler(
                    servicer.install_system_update,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.SystemUpdateInstallResponse.SerializeToString,
            ),
            'reboot': grpc.unary_unary_rpc_method_handler(
                    servicer.reboot,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'factory_reset': grpc.unary_unary_rpc_method_handler(
                    servicer.factory_reset,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_system_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_system_version,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.SystemVersionResponse.SerializeToString,
            ),
            'get_api_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_api_version,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.GetApiVersionResponse.SerializeToString,
            ),
            'get_disk_usage_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_disk_usage_stats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=moblab__common_dot_proto_dot_hostservice__pb2.GetDiskUsageStatsResponse.SerializeToString,
            ),
            'stop_ui': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_ui,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moblab.MoblabHostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MoblabHostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_host_identifier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_host_identifier',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.HostIdentifierResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_service_running(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/is_service_running',
            moblab__common_dot_proto_dot_hostservice__pb2.ServiceRunningRequest.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.ServiceRunningResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_disk_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_disk_info',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.DiskInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_cpu_temperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_cpu_temperature',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.CpuTemperatureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_ip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_ip',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.IpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_external_mac_address(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_external_mac_address',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.ExternalMacAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def check_for_system_update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/check_for_system_update',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_system_update_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_system_update_status',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.SystemUpdateStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def install_system_update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/install_system_update',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.SystemUpdateInstallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reboot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/reboot',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def factory_reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/factory_reset',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_system_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_system_version',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.SystemVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_api_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_api_version',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.GetApiVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_disk_usage_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/get_disk_usage_stats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            moblab__common_dot_proto_dot_hostservice__pb2.GetDiskUsageStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stop_ui(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/moblab.MoblabHostService/stop_ui',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
