#!/bin/bash
# Copyright 2025 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG="$(dirname "$0")/satlab.conf"
source "$CONFIG"

# --- UI Colors ---
C_YELLOW='\033[1;33m'
C_GREEN='\033[1;32m'
C_RED='\033[0;31m'
C_NC='\033[0m' # No Color


# 1. Read the current channel from the config file.
# We use a default of "release" if the line isn't found.
current_channel=$(grep "^LABEL=" "$CONFIG" | cut -d'=' -f2 | tr -d '[:space:]' || echo "release")
echo -e "Current channel is: ${C_YELLOW}$current_channel${C_NC}"

# 2. Determine the target channel.
if [[ "$current_channel" == "release" ]]; then
    target_channel="beta"
else
    target_channel="release"
fi

# 3. Ask the user if they want to switch.
# The capital 'N' indicates that "no" is the default if the user just presses Enter.
read -p "Do you want to switch to the '${target_channel}' channel? (y/n, default: no) " response

# 4. Process the response. We only proceed if the answer is explicitly 'yes'.
# The response is converted to lowercase with ,, for easier matching.
if [[ "${response,,}" =~ ^(y|yes)$ ]]; then
    echo "Switching channel to '$target_channel'..."
    set_config "LABEL" "$target_channel"

    # Verify the change was successful
    updated_channel=$(grep "^LABEL=" "$CONFIG" | cut -d'=' -f2 | tr -d '[:space:]')
    if [[ "$updated_channel" == "$target_channel" ]]; then
        echo -e "${C_GREEN}Successfully switched channel to '$updated_channel'.${C_NC}"
    else
        echo -e "${C_RED}Error: Failed to update the channel in $CONFIG.${C_NC}"
    fi
else
    echo "Keeping the current '${current_channel}' channel. No changes made."
fi
