#!/usr/bin/env bash
set e

echo "##################################"
echo "Install Satlab"
echo "##################################"
echo "We try to prepare your setup to use Satlab."
echo "Please restart the host after installing Satlab to finish initialization."

/usr/bin/bash satlab_prepare_docker

echo "Please provide followed information."
echo "All information can be updated lated by running 'satlab_install'."

/usr/bin/bash satlab_install
echo "##################################"
echo "Thank you for using Satlab."
echo ""
echo "Please reboot the host now to finish initialization."
echo "##################################"
