# Copyright 2025 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
#  found in the LICENSE file.

#  dnsmasq config, for a complete example, see:
#  http://oss.segetech.com/intra/srv/dnsmasq.conf

# disable local DNS service and provide external servers
port=0
dhcp-option=6,8.8.8.8,8.8.4.4

dhcp-range=192.168.231.10,192.168.231.250,12h
dhcp-broadcast
dhcp-hostsfile=/var/lib/misc/dhcp.hosts