#!/bin/bash
# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### BEGIN INIT INFO
# Provides:           satlab-setup
# Required-Start:     docker
# Required-Stop:      docker
# Short-Description:  Create Satlab compose to restart Satlab containers.
# Description:        Create Satlab compose to restart Satlab containers.
### END INIT INFO

# Single script to restart Satlab

. /etc/satlab/satlab.conf
##################################################################
# Data specified by user.
echo "Name used for drone: ${DRONE_HOSTNAME}"
echo "External network port: ${EXTERNAL_PORT_TO_INTERNET}"
echo "Private network port: ${INTERNAL_PORT_TO_DUTS}"
##################################################################
# Docker preparation as access to the file is always gone after reboot.
sudo chmod 666 /var/run/docker.sock
##################################################################
# Prepare network.
sudo satlab_network
##################################################################
# We do we not download security key here as no user interaction is expected.
# TODO: Need verify is key is expired or not.
##################################################################
sudo satlab_compose
sudo satlab_remote_access
