#!/bin/bash
# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### BEGIN INIT INFO
# Provides:           satlab-setup
# Required-Start:     docker
# Required-Stop:      docker
# Short-Description:  Create Satlab compose to setup Satlab containers.
# Description:        Create Satlab compose to setup Satlab containers.
### END INIT INFO

# Required to be installed bridge-utils.
# sudo apt install bridge-utils

# Single script to prepare Satlab
# Function to ask user to provide data.
. satlab_common
ask(){
   local filename=$1
   local message=$2
   local name2
   if [ -f "$filename" ]; then name="$(cat <"$filename")";else name=""; fi
   1>&2 echo -n "$message ($name): "
   read -r name2
   if [ -z "$name2" ]; then 1>&2 echo "Using $name as default value" ; else name="$name2" ;fi
   echo "$name" > "$filename"
   echo "$name"
}

# List all network interfaces
network_interfaces=$(find /sys/class/net -mindepth 1 -maxdepth 1 -lname '*virtual*' -prune -o -printf '%f\n')
select_network_interface(){
   local filename=$1
   local message=$2
   if [ -f "$filename" ]; then name="$(cat <"$filename")";else name=""; fi
   1>&2 echo "$message ($name):"
   name2=$(select opt in $network_interfaces;do echo $opt; break;done)
   if [ -z "$name2" ]; then 1>&2 echo "Using $name as default value" ; else name="$name2" ;fi
   echo "$name" > "$filename"
   echo "$name"
}
mkdir -p /etc/satlab/
##################################################################
# Collect some data from user
DRONE_HOSTNAME=$(ask "$SERVER_NAME_FILE" "Please specify Satlab name") # Name that is set for the drone.
EXT_IFACE=$(select_network_interface "$EXTERNAL_PORT_FILE" "Please specify internet port")  # Interface that is connected to the internet
INT_IFACE=$(select_network_interface "$ETHERNET_PORT_FILE" "Please specify ethernet port")  # Interface that is connected to DUT
HOSTS_FILE=/etc/hosts
echo "Name used for drone: ${DRONE_HOSTNAME}"
echo "External network port: ${EXT_IFACE}"
echo "Private network port: ${INT_IFACE}"
echo "Local file used for DNS server: ${HOSTS_FILE}"
##################################################################
# Do not edit below this line.
##################################################################
DHCPD_IFACE=qemubr0
SERVER_ADDRESS=192.168.231.1
SERVER_NETMASK=255.255.255.0

sudo brctl addbr ${DHCPD_IFACE} || true
sudo brctl setfd ${DHCPD_IFACE} 0 || true
sudo ifconfig ${DHCPD_IFACE} allmulti
sudo ifconfig "${INT_IFACE}" allmulti
sudo ifconfig ${DHCPD_IFACE} ${SERVER_ADDRESS} netmask ${SERVER_NETMASK} up
sudo brctl addif ${DHCPD_IFACE} "${INT_IFACE}"
# Creating local file for user which will be used for DHCP.
# By this file user can set mapping between Mac and IP addressess.
# File is outside to keep outside the docker and persist per server.
############################################################
# You can't have --rm and --restart on a docker run command.
# However this means that on a non clean shutdown the dhcp container is
# restarted, this causes internal/external network detection issues and
# put the moblab in a bad state.
# On boot get rid of any prior containers and make sure we have the latest
# dhcp container.
docker stop dhcp || true
docker rm dhcp || true
docker pull ${DHCP_DOCKER_IMAGE}
docker run --name dhcp -d \
    -v leases:/var/lib/misc -d \
    --restart always \
    --cap-add=NET_ADMIN \
    --network host \
    ${DHCP_DOCKER_IMAGE} \
    --interface ${DHCPD_IFACE} \
    --bind-interfaces \
    --log-dhcp

#Set sharing between interfaces.
sudo iptables -w -t nat -A POSTROUTING -o "${EXT_IFACE}" -j MASQUERADE
sudo iptables -w -A FORWARD -i "${EXT_IFACE}" -o ${DHCPD_IFACE} -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -w -A FORWARD -i ${DHCPD_IFACE} -o "${EXT_IFACE}" -j ACCEPT
sudo ifconfig "${INT_IFACE}" up
sudo iptables -w -P FORWARD ACCEPT
##################################################################
# Download service account file for compose.
# System is expected that this volume will be exist.
# TODO: Avoid authorization by verifying the downloaded key that is not expired.
echo "Create volume 'satlab_keys' to keep Satlab key."
docker volume create --name=satlab_keys
VOLUME_KEYS_FOLDER=/home/satlab/keys/
GCLOUD="docker run --rm -ti -a stdout -v satlab_keys:${VOLUME_KEYS_FOLDER} -v gcloud:/root/.config/gcloud ${CLOUD_SDK_IMAGE}"
echo "Try to autorize user!"
if ! ${GCLOUD} gcloud auth login; then
    echo "User fail to autorize!"
    exit 1
fi
echo "User autorized!"
echo "Try to download service account key!"
if ! ${GCLOUD} gsutil cp gs://satlab-keys/satlab_service_account.json ${VOLUME_KEYS_FOLDER}; then
    echo "Failed to download service account key, please try again!"
    exit 1
fi
echo "Satlab service account key downloaded!"
# Start compose for Satlab
echo "Starting preparation the host for usage"
docker rm compose --force || true
docker pull ${COMPOSE_DOCKER_IMAGE} || true
docker run -d --restart unless-stopped --name compose \
    --label=com.centurylinklabs.watchtower.lifecycle.pre-update="docker-compose down" \
    --label=com.centurylinklabs.watchtower.stop-signal=KILL \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v docker_config:/root/.docker \
    -v satlab_keys:${VOLUME_KEYS_FOLDER} \
    -v cache_server:/home/satlab/cache_server \
    -e DRONE_HOSTNAME="${DRONE_HOSTNAME}" \
    -e LABEL="${COMPOSE_LABEL}" \
    -e DRONE_AGENT_DUT_CAPACITY=60 \
    -e HOSTS_FILE="${HOSTS_FILE}" \
    --add-host dockerhost:172.17.0.1 \
    ${COMPOSE_DOCKER_IMAGE} up

# Allow port to be available outside.TODO: need working on this part.
# sudo ufw allow ${REMOTE_ACCESS_SSH_PORT}
# Remote access required access to the key which already downloaded and verified in compose.
# Remove old image always to avoid any issues with that and pull new one.
docker stop satlab_remote_access || true
docker rm satlab_remote_access || true
docker pull "${REMOTE_ACCESS_IMAGE}"
docker run -ti -d -v logs:/var/log/satlab \
  -v /var/log/bootup:/var/log/bootup \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v satlab_keys:${VOLUME_KEYS_FOLDER} \
  -v cache_server:/home/satlab/cache_server \
  -v leases:/leases:ro \
  --name satlab_remote_access \
  -e PUBLIC_KEY_FILE=/testing_rsa.pub \
  -e PUID=246 \
  -e PGID=246 \
  -e TZ=Etc/UTC \
  -e USER_NAME=moblab \
  -e DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel \
  -e SUDO_ACCESS=true \
  -p ${REMOTE_ACCESS_SSH_PORT}:2222 \
  --dns 192.168.100.51 \
  --add-host dockerhost:172.17.0.1 \
  "${REMOTE_ACCESS_IMAGE}"