#!/bin/bash
# Copyright 2022 The Chromium OS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_DIR=/etc/satlab
SERVER_NAME_FILE=$CONFIG_DIR/drone-hive
EXTERNAL_PORT_FILE=$CONFIG_DIR/external-port
ETHERNET_PORT_FILE=$CONFIG_DIR/ethernet-port

mkdir -p /etc/satlab
touch "$SERVER_NAME_FILE"
touch "$EXTERNAL_PORT_FILE"
touch "$ETHERNET_PORT_FILE"

HOSTS_FILE=/etc/hosts

# Allowed to open port 2225
REMOTE_ACCESS_SSH_PORT=2225
echo "Remote access docker container for port ${REMOTE_ACCESS_SSH_PORT}"

# Docker images used in the script
DHCP_DOCKER_IMAGE=gcr.io/chromeos-partner-moblab/moblab-dhcp:release
COMPOSE_DOCKER_IMAGE=us-docker.pkg.dev/chromeos-partner-moblab/satlab/satlab-compose:release
REMOTE_ACCESS_IMAGE=us-docker.pkg.dev/chromeos-partner-moblab/satlab/satlab_remote_access:release
# TODO: look to the option to simplify update logic for the image.
CLOUD_SDK_IMAGE=google/cloud-sdk:396.0.0-slim
