#!/bin/sh
# Copyright 2023 The Chromium OS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
set -e

### BEGIN INIT INFO
# Provides:           satlab-docker-registry
# Required-Start:     docker
# Required-Stop:      docker
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Create lightweight, portable, self-sufficient containers.
# Description: Docker registry to allow for local satlab development
### END INIT INFO


. /lib/lsb/init-functions

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting script satlab "
        satlab_restart
    ;;
    stop)
        echo "NOT IMPLEMENTED"
    ;;
    *)
        echo "Usage: /etc/init.d/satlab-init {start|stop}"
        exit 1
    ;;
esac

exit 0