#!/bin/bash
# Copyright 2023 The Chromium OS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#
# Data provided by user as part of setup process.
#
# Name that is set for the drone.
DRONE_HOSTNAME=""
# Interface that is connected to the internet
EXTERNAL_PORT_TO_INTERNET=""
# Interface that is connected to DUT
INTERNAL_PORT_TO_DUTS=""

#
# DO NOT change below settings unless instructed
#
DHCPD_IFACE=qemubr0
SERVER_ADDRESS=192.168.231.1
SERVER_NETMASK=255.255.255.0
REMOTE_ACCESS_SSH_PORT=2225


#
# Docker images used in the scripts.
#
DHCP_DOCKER_IMAGE=gcr.io/chromeos-partner-moblab/moblab-dhcp:release
COMPOSE_DOCKER_IMAGE=us-docker.pkg.dev/chromeos-partner-moblab/satlab/satlab-compose:release
REMOTE_ACCESS_IMAGE=us-docker.pkg.dev/chromeos-partner-moblab/satlab/satlab_remote_access:release
CLOUD_SDK_IMAGE=google/cloud-sdk:396.0.0-slim
