#!/bin/bash
# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### BEGIN INIT INFO
# Provides:           satlab-setup
# Required-Start:     docker
# Required-Stop:      docker
# Short-Description:  Create Satlab compose to setup Satlab containers.
# Description:        Create Satlab compose to setup Satlab containers.
### END INIT INFO

# Required to be installed bridge-utils.
# sudo apt install bridge-utils

# Single script to prepare Satlab
##################################################################
# Function to ask user to provide data.
. /etc/satlab/satlab.conf
. satlab_questions
##################################################################
# Prepare service to restart satlab as needed
systemctl daemon-reload
systemctl enable satlab.service
##################################################################
# Collect some data from user
echo "Name used for drone: ${DRONE_HOSTNAME}"
echo "External network port: ${EXTERNAL_PORT_TO_INTERNET}"
echo "Private network port: ${INTERNAL_PORT_TO_DUTS}"
##################################################################
# Docker preparation as access to the file is always gone after reboot.
chmod 666 /var/run/docker.sock
##################################################################
# Download service account file for compose.
# System is expected that this volume will be exist.
# TODO: Avoid authorization by verifying the downloaded key that is not expired.
echo "Create volume 'satlab_keys' to keep Satlab key."
docker volume create --name=satlab_keys
GCLOUD="docker run --rm -ti -a stdout -v satlab_keys:${VOLUME_KEYS_FOLDER} -v gcloud:/root/.config/gcloud ${CLOUD_SDK_IMAGE}"
echo "Try to autorize user!"
if ! ${GCLOUD} gcloud auth login; then
    echo "User fail to autorize!"
    exit 1
fi
echo "User autorized!"
echo "Try to download service account key!"
if ! ${GCLOUD} gsutil cp gs://satlab-keys/satlab_service_account.json ${VOLUME_KEYS_FOLDER}; then
    echo "Failed to download service account key, please try again!"
    exit 1
fi
echo "Satlab service account key downloaded!"
##################################################################
source satlab_restart