substitutions:
  _BASE_REGISTRY_URI: us-docker.pkg.dev/chromeos-partner-moblab/base-containers
  _REGISTRY_URI: us-docker.pkg.dev/chromeos-partner-moblab/satlab
  _SSH_PORT: "22"
  __LABEL: autopush
  _WATCHTOWER_CMD: --enable-lifecycle-hooks --interval 60 --include-restarting --label-enable
  _COMMON_CORE_LABEL: autopush
  _COMMON_CORE_URI: gcr.io/chromeos-partner-moblab
  _SFP_REGISTRY_URI: us-docker.pkg.dev/chromeos-partner-moblab/satlab-for-partners
  __BUILD_VERSION: "stable"
  # These labels/tags are part of satlab-compose
  _CONF_CREATOR: ""
  _DOWNLOADER: ""
  _NGINX: ""
  _SATLAB_DRONE: ""
  _SATLAB_RPCSERVER: ""
  _ENVOY_PROXY: ""
steps:
  - id: docker-compose
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "${_BASE_REGISTRY_URI}/docker/compose:alpine-1.27.4"]
    waitFor: ['-']
  - id: moblab-common
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "${_COMMON_CORE_URI}/moblab_common:${_COMMON_CORE_LABEL}"]
    waitFor: ['-']
  - id: remote-access
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "${_COMMON_CORE_URI}/remote_access:${_COMMON_CORE_LABEL}"]
    waitFor: ['-']
  - id: envoyproxy
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "${_BASE_REGISTRY_URI}/envoyproxy/envoy:v1.15.2"]
  - id: blacklabelops_logrotate
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "${_BASE_REGISTRY_URI}/blacklabelops/logrotate:latest"]
    waitFor: ['-']
  - id: compose
    name: "gcr.io/cloud-builders/docker"
    dir: src
    args:
      [
        "build",
        "--build-arg", "CONF_CREATOR_VER=${_CONF_CREATOR}",
        "--build-arg", "DOWNLOADER_VER=${_DOWNLOADER}",
        "--build-arg", "NGINX_VER=${_NGINX}",
        "--build-arg", "SATLAB_DRONE_VER=${_SATLAB_DRONE}",
        "--build-arg", "SATLAB_RPCSERVER_VER=${_SATLAB_RPCSERVER}",
        "--build-arg", "ENVOY_PROXY_VER=${_ENVOY_PROXY}",
        "--build-arg", "REGISTRY_URI=${_REGISTRY_URI}",
        "--build-arg", "LABEL=${__LABEL}",
        "--build-arg", "COMMON_CORE_LABEL=${_COMMON_CORE_LABEL}",
        "--build-arg", "COMMON_CORE_URI=${_COMMON_CORE_URI}",
        "--build-arg", "BASE_REGISTRY_URI=${_BASE_REGISTRY_URI}",
        "--build-arg", "SFP_REGISTRY_URI=${_SFP_REGISTRY_URI}",
        "--build-arg", "BUILD_VERSION=${__BUILD_VERSION}",
        "--label=version=${__BUILD_VERSION}",
        "-t", "${_REGISTRY_URI}/satlab-compose:${__LABEL}",
        "-f", "dockerfiles/compose/Dockerfile",
        "."
      ]
    env:
      - "DOCKER_BUILDKIT=1"
      - "WATCHTOWER_CMD=${_WATCHTOWER_CMD}"
    waitFor:
     - "docker-compose"
     - "moblab-common"

  - id: satlab-remote-access
    name: "gcr.io/cloud-builders/docker"
    dir: src
    args:
      [
        "build",
        "--build-arg", "REGISTRY_URI=${_REGISTRY_URI}",
        "--build-arg", "LABEL=${__LABEL}",
        "--build-arg", "COMMON_CORE_LABEL=${_COMMON_CORE_LABEL}",
        "--build-arg", "COMMON_CORE_URI=${_COMMON_CORE_URI}",
        "--build-arg", "BASE_REGISTRY_URI=${_BASE_REGISTRY_URI}",
        "--build-arg", "BUILD_VERSION=${__BUILD_VERSION}",
        "-t", "${_REGISTRY_URI}/satlab_remote_access:${__LABEL}",
        "-f", "dockerfiles/satlab_remote_access/Dockerfile",
        "."
      ]
    env:
      - "DOCKER_BUILDKIT=1"
      - "SSH_PORT=${_SSH_PORT}"
    waitFor:
     - "remote-access"

  - id: satlab-rpcserver
    name: "gcr.io/cloud-builders/docker"
    dir: src
    args:
      [
        "build",
        "--build-arg", "REGISTRY_URI=${_REGISTRY_URI}",
        "--build-arg", "LABEL=${__LABEL}",
        "--build-arg", "COMMON_CORE_LABEL=${_COMMON_CORE_LABEL}",
        "--build-arg", "COMMON_CORE_URI=${_COMMON_CORE_URI}",
        "--build-arg", "BASE_REGISTRY_URI=${_BASE_REGISTRY_URI}",
        "--build-arg", "BUILD_VERSION=${__BUILD_VERSION}",
        "-t", "${_REGISTRY_URI}/satlab-rpcserver:${__LABEL}",
        "-f", "dockerfiles/satlab-rpcserver/Dockerfile",
        "."
      ]
    env:
      - "DOCKER_BUILDKIT=1"
    waitFor:
     - "moblab-common"

  - id: envoy
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg", "REGISTRY_URI=${_REGISTRY_URI}",
        "--build-arg", "LABEL=${__LABEL}",
        "-t", "${_REGISTRY_URI}/envoy-proxy:${__LABEL}",
        "-f", "dockerfiles/envoy/Dockerfile",
        "."
      ]
    waitFor:
      - "envoyproxy"

  - id: logrotate
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg", "REGISTRY_URI=${_REGISTRY_URI}",
        "--build-arg", "LABEL=${__LABEL}",
        "--build-arg", "BUILD_VERSION=${__BUILD_VERSION}",
        "-t", "${_REGISTRY_URI}/logrotate:${__BUILD_VERSION}",
        "-f", "/workspace/src/dockerfiles/utilities/Dockerfile.logrotate",
        "/workspace/src/dockerfiles/utilities/",
      ]
    # TODO: add additional variables to the build process at later point
    # env:
    #   - "DOCKER_BUILDKIT=1"
    waitFor:
      - "blacklabelops_logrotate"

images:
  [
    "${_REGISTRY_URI}/satlab-compose:${__LABEL}",
    "${_REGISTRY_URI}/satlab_remote_access:${__LABEL}",
    "${_REGISTRY_URI}/satlab-rpcserver:${__LABEL}",
    "${_REGISTRY_URI}/envoy-proxy:${__LABEL}",
    "${_REGISTRY_URI}/logrotate:${__LABEL}",
  ]

options:
  # Use higher CPU machines so the caching and build steps are faster.
  machineType: "N1_HIGHCPU_32"
  substitution_option: "ALLOW_LOOSE"

timeout: 18000s
