export LABEL := ${USER}
export REGISTRY := gcr.io/chromeos-partner-moblab
export SATLAB_REGISTRY := gcr.io/satlab-images
export CACHE_SERVER_REGISTRY := gcr.io/chromeos-cacheserver-images
export BUILD_VERSION := ${LABEL}
SSH_PORT := 22
-include local_registry.mk
include common.mk