#!/usr/bin/python3

# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""This command adds a DUT to UFS and runs a deploy task for satlab.

Add-dut runs in the satlab-remote-access container and automates the
task of deploying a DUT.

TODO(gregorynisbet): Add example usage.
"""

import argparse
import datetime
import logging
import subprocess
import sys
import time

# Log in a dedicated file under /var/log/satlab.
# TODO(gregorynisbet): Consider other logging strategies
# besides a single file.
LOG_ROOT = '/var/log/satlab'
LOG_PATH = '%s/add-dut.log' % LOG_ROOT

parser = argparse.ArgumentParser(description='Add a DUT')
parser.add_argument('--hostname', type=str)
parser.add_argument('--non-interactive', action='store_true', default=False)
parser.add_argument('--debug', action='store_true', default=False)


def initialize_logging():
  """Configure logging rooted at /var/log/satlab.

  /var/log is mounted from the DHB.
  We log immediately, write a debug message immediately,
  and then crash if we cannot write a startup message.
  """
  try:
    logging.basicConfig(filename=LOG_PATH, filemode='a', level=logging.DEBUG)
    start_time = time.time()
    logging.debug('add-dut invoked at %s (%s)', start_time,
                  datetime.datetime.fromtimestamp(start_time))
  except FileNotFoundError as e:
    eprint('Failed to initialize logging. Cannot write to %s', LOG_PATH)
    eprint(e)
    sys.exit(1)
  except PermissionError as e:
    eprint('Failed to initialize logging. No permission to write to %s',
           LOG_PATH)
    eprint(e)
    sys.exit(1)


def eprint(*args, **kwargs) -> None:
  """Write a message to stderr."""
  return print(*args, file=sys.stderr, **kwargs)


def main() -> int:
  """Add a DUT."""
  initialize_logging()
  _ = vars(parser.parse_args())
  try:
    ensure_rack()
  except FileNotFoundError as e:
    eprint(e)
    return 1
  except subprocess.CalledProcessError as e:
    eprint(e)
    return 1
  return 0


def ensure_rack() -> None:
  """Ensure that the rack for the given satlab instance exists."""
  subprocess.check_call(['/usr/local/bin/shivas_ensure_rack'])


if __name__ == '__main__':
  sys.exit(main())
