#!/bin/bash

# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Update all the packages in the cipd directory at once.

sudo /root/depot_tools/cipd ensure -root /cipd -ensure-file /cipd/spec
