#!/bin/sh
# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# get_host_mac gets the external MAC address for the satlab host.

set -eu

exec python3 /usr/local/bin/host_command.py "$0"
