#!/bin/sh
# Copyright 2023 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# get_disk_info does df -h and lsblk.

set -eu

exec python3 /usr/local/bin/host_command.py "$0"
