#!/bin/bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Folder where all the keys/configs are stored
KEYS_FOLDER=/home/satlab/keys
# TODO(prasadv): Move this to environment variable
GCLOUD_SDK_VERSION=396.0.0
# Docker command to run gcloud sdk
GCLOUD="docker run --rm -ti -a stdout -v satlab_keys:${KEYS_FOLDER} -v gcloud:/root/.config/gcloud google/cloud-sdk:${GCLOUD_SDK_VERSION}-slim"
# Satlab configuration file name to be downloaed from GCS
SATLAB_CONFIG_FILENAME=satlab-config.json
# Directory where the .env file is stored
SATLAB_ENV_DIR=/home/satlab/config
# File path to the .env file where environmental variables are stored
SATLAB_ENV_FILE=${SATLAB_ENV_DIR}/.env
# Service account key file name
SATLAB_SA_FILENAME="pubsub-key-do-not-delete.json"

clear >$(tty)
cat << EOF
###############################################################################
IMPORTANT: Please read below information
###############################################################################
Setting up Satlab requires special privileges, you need access to
the Google Storage Bucket and to download artifacts.
This script will authenticate the user to access the required artifacts.

The following the are steps this script executes:

1. Asks for Google Storage Bucket name

  *  Google Partners have to provide the GS bucket information assigned to them.

  *  Satlab internal users(googlers), please use "chromeos-satlab-internal-users"
     as your GS bucket

2. Authenticate user using GCloud SDK(uses gcloud-sdk docker container),
   when prompted please use your account(@google.com or Partner Domain account)
3. Pulls in required artifacts once the user is verified.
4. Finally reboots the chromebox. (You must restart the chromebox inorder to
   finish the satlab setup)
###############################################################################

EOF
while true; do
    read -p "Do you want to continue with the Satlab setup(y/n)?" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

# This function takes JSON file as input and parses key-values to env
# vairables, then store in .env file.
function create_env_file() {
  CONFIG_FILE=$1

  # Check if the JSON file exists.
  if [ ! -f "${CONFIG_FILE}" ]; then
    echo -e "ERROR: The Satlab config file '$CONFIG_FILE' does not exist.\n"
    exit 1
  fi
  # Creat and empty .env file, delete content if file already exists
  > ${SATLAB_ENV_FILE}

  # Read the JSON file into a temporary file
  TMP_FILE=$(mktemp)
  sed '/\/\//d' "${CONFIG_FILE}" | jq -r 'to_entries[] | [.key, .value] | join("=")' > "${TMP_FILE}"
  if [ "$?" -ne 0 ]; then
    echo -e "\nERROR: Failed parse the Satlab Configuration file, aborting setup!"
    exit
  fi

  # Write each key-value pair as an environment variable in .env file
  while IFS='=' read -r key value; do
    echo "$key=$value" >> ${SATLAB_ENV_FILE}
  done < "${TMP_FILE}"
  # Delete the temporary file
  rm "${TMP_FILE}"
}

echo -e "\nStarting Satlab setup.....\n"
read -p "Please enter your GS Bucket name (for details pls read the instructions above): " PROJECT_GS_BUCKET
echo -e "\nAuthenticating the user, please follow the instructions..."

${GCLOUD} gcloud auth login
if [ "$?" -ne 0 ]; then
  echo -e "\nERROR:Failed to authenticate the user, you must use your @google.com account. Please try again!"
  exit
fi

# TODO (anhdle): Enable mutilple service accounts when easier user workflow is available
# read -p "Please specify the service account: " sa
# echo "Create and download service account key..."
# ${GCLOUD} gcloud iam service-accounts keys create "${KEYS_FOLDER}/satlab_service_account.json" --iam-account="$sa"
# if [ "$?" -ne 0 ]; then
#   echo "Failed to create service account key, please try again!"
#   exit
# fi

echo
echo "Downloading artifacts..."
# Download service account key since 10 keys limit per service account.
# TODO (anhdle): Investigate Wwrkload identity federation
${GCLOUD} gsutil cp gs://${PROJECT_GS_BUCKET}/${SATLAB_SA_FILENAME} ${KEYS_FOLDER}
if [ "$?" -ne 0 ]; then
  echo -e "\nERROR:Failed to download service account key, please try again!"
  exit
fi
sudo chmod 666 ${KEYS_FOLDER}/${SATLAB_SA_FILENAME}

# Download Satlab configuration file.
${GCLOUD} gsutil cp gs://${PROJECT_GS_BUCKET}/${SATLAB_CONFIG_FILENAME} ${KEYS_FOLDER}

if [ "$?" -ne 0 ]; then
  echo -e "\nERROR:Failed to download Satlab Configuration file please try again!"
  exit
fi

if [[ -f "${KEYS_FOLDER}/${SATLAB_CONFIG_FILENAME}" && -d "${SATLAB_ENV_DIR}" ]]; then
  # Convert JSON file content to environmental variables
  create_env_file  ${KEYS_FOLDER}/${SATLAB_CONFIG_FILENAME}
fi

echo -e "\nSatlab setup successful, please reboot\n"

while true; do
    read -p "Do you want to reboot now(y/n)?" yn
    case $yn in
        [Yy]* ) reboot;;
        [Nn]* ) echo "You MUST restart to apply start Satlab"
                exit;;
        * ) echo "Please answer yes or no.";;
      esac
done
