#!/bin/sh
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# shellcheck disable=SC2065

# Ensure the existence of a labstation associated with the current satlab.
# This command is idempotent. It can be run any number of times.

# TODO(gregorynisbet): Remove this command once we can verify that the labstation-less
# deployment works in a satlab dev environment (i.e. servod container has landed).

set -x

# Always run shivas in the os namespace.
SHIVAS_NAMESPACE=os; export SHIVAS_NAMESPACE

# Die prints lines to stderr and then exits abnormally.
die() {
        printf "%s\n" "$@" 1>&2
        exit 1
}

# Check for the existence of the tools we depend on up front.
test -e /usr/local/bin/shivas 1>/dev/null || die 'no shivas tool'
test -x /usr/local/bin/shivas 1>/dev/null || die 'shivas not executable file'
test -e /usr/local/bin/get_host_identifier 1>/dev/null || die 'no get_host_identifier tool'
test -x /usr/local/bin/get_host_identifier 1>/dev/null || die 'get_host_identifier not executable file'

# Parse the arguments.
# TODO(gregorynisbet): Make the arguments non-positional
asset_tag="$1"
model="$2"
board="$3"
hostname_suffix="$4"

# Validate the arguments.
test -n "$asset_tag"        || die 'need asset tag (1st argument)'
test -n "$model"            || die 'need model (2nd argument)'
test -n "$board"            || die 'need board (3rd argument)'
test -n "$hostname_suffix"  || die 'need hostname suffix (4th argument)'

# Get the satlab serial number.
host_identifier="$(/usr/local/bin/get_host_identifier)" || die 'failed to get host identifier (satlab serial)'
test -n "$host_identifier" || die 'host identifier (satlab serial) unexpectedly empty'

# Set the full DUT hostname.
# Example: satlab-1aaaaaaa3333333-labstation1
hostname="satlab-${host_identifier}-${hostname_suffix}"


# Try to add the asset.
if test -n "$(/usr/local/bin/shivas get -json asset "$asset_tag")"; then
        : "do nothing"
else
        /usr/local/bin/shivas add asset -name "$asset_tag" -rack pv-rack -zone satlab -model "$model" -board "$board" -type labstation 1>&2
fi

# Try to add the labstation.
if test -n "$(/usr/local/bin/shivas get dut "$hostname")"; then
        /usr/local/bin/shivas add labstation -name "$hostname" -asset "$asset_tag" -pools satlab 1>&2
fi

# TODO(gregorynisbet): Add labstation to local DNS entry.
