#!/bin/sh
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# shellcheck disable=SC2065

# Ensure the existence of a shivas rack associated with the current satlab.
# This command is idempotent. It can be run any number of times.

# Always run shivas in the os namespace.
SHIVAS_NAMESPACE=os; export SHIVAS_NAMESPACE

# Die prints lines to stderr and then exits abnormally.
die() {
        printf "%s\n" "$@" 1>&2
        exit 1
}

# Ewriteln writes lines to stderr.
ewriteln() {
        printf "%s\n" "$@" 1>&2
}

# Exit successfully with a message.
succeed() {
        printf "%s\n" "$@" 1>&2
        exit 0
}

# Check for the existence of the tools we depend on up front.
test -e /usr/local/bin/shivas 1>/dev/null || die 'no shivas tool'
test -x /usr/local/bin/shivas 1>/dev/null || die 'shivas not executable file'
test -e /usr/local/bin/get_host_identifier 1>/dev/null || die 'no get_host_identifier tool'
test -x /usr/local/bin/get_host_identifier 1>/dev/null || die 'get_host_identifier not executable file'

# Get the satlab serial number.
host_identifier="$(/usr/local/bin/get_host_identifier)" || die 'failed to get host identifier (satlab serial)'
test -n "$host_identifier" || die 'host identifier (satlab serial) unexpectedly empty'

rack_name="${host_identifier}-rack"

# Try to get information about the rack. Exit successfully if the rack already exists.
/usr/local/bin/shivas get rack -name "$rack_name" 1>/dev/null && succeed "$rack_name already exists"

# Otherwise try to add it.
exec /usr/local/bin/shivas add rack -name "$rack_name" -zone satlab
