#!/bin/sh
# Copyright 2025 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# stop_ui stops OS UI of the satlab host.

set -eu

exec python3 /usr/local/bin/host_command.py "$0"
